name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd estoque-backend
          npm install
          cd ../estoque-frontend
          npm install

      - name: Run tests
        run: |
          cd estoque-backend
          npm test
          cd ../estoque-frontend
          npm test

      - name: Build frontend
        run: |
          cd estoque-frontend
          npm run build

      - name: Deploy
        run: |
          echo "Deploying application..."
          # Adicione seu script de deploy aqui 